version: "3.8"

services:
  backend:
    build: .
    container_name: backend
    ports:
      - "3333:3333"
    volumes:
      - .:/app
    env_file:
      - .env
    depends_on:
      - minio

  minio:
    image: minio/minio:RELEASE.2025-02-03T21-03-04Z-cpuv1
    container_name: minio
    ports:
      - "9000:9000"
      - "9001:9001"
    environment:
      MINIO_ROOT_USER: test@mt2024
      MINIO_ROOT_PASSWORD: test@mt2024
    command: server --console-address ":9001" /data
    volumes:
      - minio_data:/data

volumes:
  minio_data:
